In [1]:
#import libraries
import os
import numpy as np
import pandas as pd
import timeit

from sklearn.model_selection import train_test_split, RepeatedKFold, GroupKFold
from sklearn.linear_model import Ridge, RidgeCV, LassoCV, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import geopandas as gpd
import seaborn as sns
import matplotlib.cm
import matplotlib.pyplot as plt
%matplotlib inline

## import MOSAIKS features

In [2]:
# import the first file 
df1 = pd.read_pickle(r'C:\HDRO\Stats\Stats2\MOSAIKS\DHS_DHS_dense_DHSID.p')
df1['ID']= df1['DHSID'].str.slice(0,2)
df1['year']= df1['DHSID'].str.slice(2,6)

In [3]:
# import the additinal file with 8 countries 
df2 = pd.read_pickle(r'C:\HDRO\Stats\Stats2\MOSAIKS\DHS_additional_global_dense_DHSID.p')
df2.columns = df2.columns.str.replace('dhsid', 'DHSID')
df2['ID']= df2['DHSID'].str.slice(0,2)
df2['year']= df2['DHSID'].str.slice(2,6)

In [4]:
# merge two datasets - this is the final dataset
df3 = pd.concat([df1, df2])
df4 = df3.drop(columns=['continent', 'ID', 'year'])

## Import NL features

In [5]:
nl = pd.read_pickle("C:/HDRO/Stats/Stats2/MOSAIKS/all_dhs_dmsp_nightlight_features_20_bins_GPW_pop_weighted.p")

In [6]:
nl

,perc_pixels_in_bin_0,perc_pixels_in_bin_1,perc_pixels_in_bin_2,perc_pixels_in_bin_3,perc_pixels_in_bin_4,perc_pixels_in_bin_5,perc_pixels_in_bin_6,perc_pixels_in_bin_7,perc_pixels_in_bin_8,perc_pixels_in_bin_9,perc_pixels_in_bin_10,perc_pixels_in_bin_11,perc_pixels_in_bin_12,perc_pixels_in_bin_13,perc_pixels_in_bin_14,perc_pixels_in_bin_15,perc_pixels_in_bin_16,perc_pixels_in_bin_17,perc_pixels_in_bin_18,perc_pixels_in_bin_19
DHSID,,,,,,,,,,,,,,,,,,,,
CM201800000018,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EG201401460501,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GN201800000186,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
KE201400000266,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
PK201700000094,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RW201900000494,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RW201900000495,0.0,0.834223,0.038776,0.048623,0.041006,0.024467,0.012905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RW201900000496,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RW201900000497,0.0,0.825554,0.048056,0.052184,0.066388,0.007817,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RW201900000500,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Import income

In [7]:
# import income file
df_list = []
direct2 = ("C:/HDRO/Stats/Stats2/geo-inc/")
for file in os.listdir(direct2 + 'geo-income_module'):
    d = pd.read_stata(direct2 + 'geo-income_module/' + file)
    df_list.append(d)
df_inc = pd.concat(df_list)

In [8]:
income = df_inc.groupby("DHSID")[["lognormal_inc_ind_wiid"]].agg(np.nanmean).dropna()

In [9]:
income

                lognormal_inc_ind_wiid
DHSID
AL201700000001            18942.701172
AL201700000002            18275.437500
AL201700000003            19139.130859
AL201700000004            20030.707031
AL201700000005            22517.060547
...                                ...
ZM201800000541             7729.175293
ZM201800000542              894.005615
ZM201800000543             3261.351807
ZM201800000544              769.586426
ZM201800000545             1706.375366

[54278 rows x 1 columns]

## Import MPI data

In [10]:
#mpi file
direct = ("C:/HDRO/Stats/Stats2/MOSAIKS/")
df_mpi = pd.read_stata(direct + "mpi_geo37.dta")

In [11]:
dep_score = df_mpi.groupby("DHSID")[["weighted_deprivation_score"]].agg(np.nanmean).dropna()

In [12]:
dep_score

                weighted_deprivation_score
DHSID
AL201700000001                    0.019204
AL201700000002                    0.009615
AL201700000003                    0.000000
AL201700000004                    0.024024
AL201700000005                    0.004274
...                                    ...
ZM201800000541                    0.178197
ZM201800000542                    0.367798
ZM201800000543                    0.284661
ZM201800000544                    0.544444
ZM201800000545                    0.348624

[52983 rows x 1 columns]

## Import IWI data

In [13]:
#iwi data
iwi = pd.read_csv(r'C:\HDRO\Stats\Stats2\MOSAIKS\mean_IWI.csv')
iwi = iwi.groupby("DHSID")[["IWI"]].mean()

In [14]:
iwi

                      IWI
DHSID
AL201700000001  89.465391
AL201700000002  86.485039
AL201700000003  87.642180
AL201700000004  86.776051
AL201700000005  89.517279
...                   ...
ZW201500000396  38.506412
ZW201500000397  41.553372
ZW201500000398  31.797095
ZW201500000399  69.709118
ZW201500000400  37.297187

[53225 rows x 1 columns]

## join all data

In [15]:
merge1 = pd.merge(df4, nl, on=['DHSID'], how="inner")

In [16]:
merge2 = pd.merge(merge1, income, on=['DHSID'], how="inner")
merge3 = pd.merge(merge2, dep_score, on=['DHSID'], how="inner")
#merge4 = pd.merge(merge3, iwi, on=['DHSID'], how="inner")

In [17]:
merge3

,DHSID,X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,perc_pixels_in_bin_12,perc_pixels_in_bin_13,perc_pixels_in_bin_14,perc_pixels_in_bin_15,perc_pixels_in_bin_16,perc_pixels_in_bin_17,perc_pixels_in_bin_18,perc_pixels_in_bin_19,lognormal_inc_ind_wiid,weighted_deprivation_score
0,AL201700000001,0.247140,0.503159,0.114064,0.203914,0.353395,0.727176,0.218433,0.306100,0.130447,...,0.000000,0.088234,0.235019,0.082250,0.393638,0.045660,0.000000,0.000000,18942.701172,0.019204
1,AL201700000002,0.218926,0.439225,0.103380,0.159651,0.315144,0.711148,0.225437,0.287943,0.098494,...,0.000000,0.108216,0.201556,0.110626,0.306916,0.000000,0.000000,0.000000,18275.437500,0.009615
2,AL201700000003,0.239452,0.515465,0.107474,0.204323,0.362553,0.710463,0.200439,0.286575,0.131596,...,0.000000,0.079555,0.229501,0.081326,0.306956,0.000000,0.000000,0.000000,19139.130859,0.000000
3,AL201700000004,0.230399,0.462435,0.107077,0.179146,0.332637,0.714292,0.223447,0.293186,0.113443,...,0.000000,0.093172,0.173535,0.095246,0.359493,0.052875,0.000000,0.000000,20030.707031,0.024024
4,AL201700000005,0.247140,0.503159,0.114064,0.203914,0.353395,0.727176,0.218433,0.306100,0.130447,...,0.000000,0.088234,0.235019,0.082250,0.393638,0.045660,0.000000,0.000000,22517.060547,0.004274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52633,RW201900000496,0.108982,0.350792,0.034645,0.137668,0.199491,0.341322,0.128825,0.150607,0.096750,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1787.015991,0.287234
52634,RW201900000497,0.138619,0.435800,0.039662,0.223957,0.251421,0.378330,0.129759,0.135954,0.172089,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1555.878784,0.369976
52635,RW201900000498,0.076103,0.296412,0.011021,0.264386,0.153407,0.179054,0.067392,0.056701,0.228597,...,0.015972,0.000000,0.015896,0.074712,0.000000,0.247376,0.140741,0.441666,3548.524414,0.210101
52636,RW201900000499,0.149145,0.475971,0.049168,0.185751,0.274041,0.468409,0.161029,0.185322,0.124372,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3598.289551,0.247942
52637,RW201900000500,0.107966,0.398365,0.019051,0.375223,0.208639,0.252725,0.103795,0.091489,0.329207,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.696899,0.384774

In [18]:
#get the log of income
merge3['loginc'] = np.log(merge3['lognormal_inc_ind_wiid'])

In [19]:
#checking for missing
merge3.isnull().sum()

DHSID                         0
X_0                           0
X_1                           0
X_2                           0
X_3                           0
                             ..
perc_pixels_in_bin_18         0
perc_pixels_in_bin_19         0
lognormal_inc_ind_wiid        0
weighted_deprivation_score    0
loginc                        0
Length: 4024, dtype: int64

In [20]:
#getting the ID
merge3['ID']= merge3['DHSID'].str.slice(0,2)

# #getiing the numeric id
# merge4['ID_n'] = merge4['ID'].factorize()[0] + 1

# #moving the id in the front
# merge4.insert(1, 'ID_n1', merge4['ID_n'])

In [21]:
merge3.insert(1, 'country', merge3['ID'])
merge4 = merge3.drop(['DHSID', "ID"], axis=1)
merge4

,country,X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,perc_pixels_in_bin_13,perc_pixels_in_bin_14,perc_pixels_in_bin_15,perc_pixels_in_bin_16,perc_pixels_in_bin_17,perc_pixels_in_bin_18,perc_pixels_in_bin_19,lognormal_inc_ind_wiid,weighted_deprivation_score,loginc
0,AL,0.247140,0.503159,0.114064,0.203914,0.353395,0.727176,0.218433,0.306100,0.130447,...,0.088234,0.235019,0.082250,0.393638,0.045660,0.000000,0.000000,18942.701172,0.019204,9.849174
1,AL,0.218926,0.439225,0.103380,0.159651,0.315144,0.711148,0.225437,0.287943,0.098494,...,0.108216,0.201556,0.110626,0.306916,0.000000,0.000000,0.000000,18275.437500,0.009615,9.813313
2,AL,0.239452,0.515465,0.107474,0.204323,0.362553,0.710463,0.200439,0.286575,0.131596,...,0.079555,0.229501,0.081326,0.306956,0.000000,0.000000,0.000000,19139.130859,0.000000,9.859490
3,AL,0.230399,0.462435,0.107077,0.179146,0.332637,0.714292,0.223447,0.293186,0.113443,...,0.093172,0.173535,0.095246,0.359493,0.052875,0.000000,0.000000,20030.707031,0.024024,9.905022
4,AL,0.247140,0.503159,0.114064,0.203914,0.353395,0.727176,0.218433,0.306100,0.130447,...,0.088234,0.235019,0.082250,0.393638,0.045660,0.000000,0.000000,22517.060547,0.004274,10.022029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52633,RW,0.108982,0.350792,0.034645,0.137668,0.199491,0.341322,0.128825,0.150607,0.096750,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1787.015991,0.287234,7.488303
52634,RW,0.138619,0.435800,0.039662,0.223957,0.251421,0.378330,0.129759,0.135954,0.172089,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1555.878784,0.369976,7.349796
52635,RW,0.076103,0.296412,0.011021,0.264386,0.153407,0.179054,0.067392,0.056701,0.228597,...,0.000000,0.015896,0.074712,0.000000,0.247376,0.140741,0.441666,3548.524414,0.210101,8.174287
52636,RW,0.149145,0.475971,0.049168,0.185751,0.274041,0.468409,0.161029,0.185322,0.124372,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3598.289551,0.247942,8.188214
52637,RW,0.107966,0.398365,0.019051,0.375223,0.208639,0.252725,0.103795,0.091489,0.329207,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.696899,0.384774,7.087320

In [22]:
#FINAL DATA
merge4

,country,X_0,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,...,perc_pixels_in_bin_13,perc_pixels_in_bin_14,perc_pixels_in_bin_15,perc_pixels_in_bin_16,perc_pixels_in_bin_17,perc_pixels_in_bin_18,perc_pixels_in_bin_19,lognormal_inc_ind_wiid,weighted_deprivation_score,loginc
0,AL,0.247140,0.503159,0.114064,0.203914,0.353395,0.727176,0.218433,0.306100,0.130447,...,0.088234,0.235019,0.082250,0.393638,0.045660,0.000000,0.000000,18942.701172,0.019204,9.849174
1,AL,0.218926,0.439225,0.103380,0.159651,0.315144,0.711148,0.225437,0.287943,0.098494,...,0.108216,0.201556,0.110626,0.306916,0.000000,0.000000,0.000000,18275.437500,0.009615,9.813313
2,AL,0.239452,0.515465,0.107474,0.204323,0.362553,0.710463,0.200439,0.286575,0.131596,...,0.079555,0.229501,0.081326,0.306956,0.000000,0.000000,0.000000,19139.130859,0.000000,9.859490
3,AL,0.230399,0.462435,0.107077,0.179146,0.332637,0.714292,0.223447,0.293186,0.113443,...,0.093172,0.173535,0.095246,0.359493,0.052875,0.000000,0.000000,20030.707031,0.024024,9.905022
4,AL,0.247140,0.503159,0.114064,0.203914,0.353395,0.727176,0.218433,0.306100,0.130447,...,0.088234,0.235019,0.082250,0.393638,0.045660,0.000000,0.000000,22517.060547,0.004274,10.022029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52633,RW,0.108982,0.350792,0.034645,0.137668,0.199491,0.341322,0.128825,0.150607,0.096750,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1787.015991,0.287234,7.488303
52634,RW,0.138619,0.435800,0.039662,0.223957,0.251421,0.378330,0.129759,0.135954,0.172089,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1555.878784,0.369976,7.349796
52635,RW,0.076103,0.296412,0.011021,0.264386,0.153407,0.179054,0.067392,0.056701,0.228597,...,0.000000,0.015896,0.074712,0.000000,0.247376,0.140741,0.441666,3548.524414,0.210101,8.174287
52636,RW,0.149145,0.475971,0.049168,0.185751,0.274041,0.468409,0.161029,0.185322,0.124372,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3598.289551,0.247942,8.188214
52637,RW,0.107966,0.398365,0.019051,0.375223,0.208639,0.252725,0.103795,0.091489,0.329207,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.696899,0.384774,7.087320

In [23]:
unique_values = merge4['country'].unique()

In [24]:
unique_values

array(['AL', 'AM', 'AO', 'BJ', 'BU', 'CM', 'EG', 'ET', 'GA', 'GN', 'GU',
       'HT', 'JO', 'KE', 'KM', 'LB', 'ML', 'MM', 'NG', 'PH', 'PK', 'SL',
       'SN', 'TJ', 'TL', 'TZ', 'UG', 'ZA', 'ZM', 'BF', 'GM', 'IA', 'KH',
       'MR', 'MZ', 'NI', 'RW'], dtype=object)

## within country analysis

In [25]:
# define a function to demean columns
def demean_column(grouped_col):
    return grouped_col - grouped_col.mean()

# group by the 'country' column and apply the demean function to each column
demeaned_df = merge4.iloc[:, 2:4025].groupby(merge4['country']).apply(demean_column)

#joining the countyr column back
demeaned_df = demeaned_df.join(merge4['country'])

In [26]:
demeaned_df

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,...,perc_pixels_in_bin_14,perc_pixels_in_bin_15,perc_pixels_in_bin_16,perc_pixels_in_bin_17,perc_pixels_in_bin_18,perc_pixels_in_bin_19,lognormal_inc_ind_wiid,weighted_deprivation_score,loginc,country
0,0.084621,0.016802,0.034896,0.050608,0.057155,0.021160,-0.029396,0.021411,0.051269,0.051879,...,0.206662,0.057360,0.356938,-0.002086,-0.041036,-0.124213,5244.280273,-0.030550,0.437517,AL
1,0.020687,0.006118,-0.009367,0.012356,0.041126,0.028163,-0.047553,-0.010542,0.001740,0.007044,...,0.173199,0.085735,0.270216,-0.047746,-0.041036,-0.124213,4577.016602,-0.040139,0.401657,AL
2,0.096926,0.010211,0.035305,0.059765,0.040441,0.003166,-0.048921,0.022561,0.033992,0.042326,...,0.201144,0.056436,0.270256,-0.047746,-0.041036,-0.124213,5440.709961,-0.049755,0.447834,AL
3,0.043896,0.009814,0.010128,0.029849,0.044270,0.026173,-0.042310,0.004407,0.017624,0.026070,...,0.145179,0.070356,0.322793,0.005129,-0.041036,-0.124213,6332.286133,-0.025731,0.493365,AL
4,0.084621,0.016802,0.034896,0.050608,0.057155,0.021160,-0.029396,0.021411,0.051269,0.051879,...,0.206662,0.057360,0.356938,-0.002086,-0.041036,-0.124213,8818.639648,-0.045481,0.610373,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52633,-0.040447,0.001694,-0.118003,-0.024413,0.025389,0.023106,0.032358,-0.109825,-0.013265,-0.081719,...,-0.005089,-0.007437,-0.004712,-0.009241,-0.009473,-0.038477,-399.525513,-0.025489,-0.032187,RW
52634,0.044561,0.006710,-0.031714,0.027516,0.062397,0.024040,0.017706,-0.034486,0.037715,0.004387,...,-0.005089,-0.007437,-0.004712,-0.009241,-0.009473,-0.038477,-630.662720,0.057254,-0.170693,RW
52635,-0.094827,-0.021930,0.008714,-0.070498,-0.136880,-0.038327,-0.061547,0.022022,-0.098437,-0.042384,...,0.010807,0.067275,-0.004712,0.238135,0.131268,0.403188,1361.982910,-0.102622,0.653798,RW
52636,0.084732,0.016217,-0.069920,0.050136,0.152476,0.055310,0.067074,-0.082203,0.089818,-0.000830,...,-0.005089,-0.007437,-0.004712,-0.009241,-0.009473,-0.038477,1411.748047,-0.064780,0.667725,RW
52637,0.007127,-0.013901,0.119551,-0.015266,-0.063209,-0.001924,-0.026760,0.122632,-0.053778,0.053047,...,-0.005089,-0.007437,-0.004712,-0.009241,-0.009473,-0.038477,-989.844604,0.072051,-0.433169,RW

## MOSAIKS model

In [41]:
#assign variables
data = demeaned_df.values

#select X features
X = data[:, 0:3999]

#create empty cell for resutls
results = []


# loop through each Y variable
for y_var in ['weighted_deprivation_score', 'loginc']:
    
    # select the current Y variable
    y = demeaned_df[y_var]
    
    # divide data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
    
    # define model evaluation method (k-fold crosss validation model)
    cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=111)

    # define model
    model = RidgeCV(alphas=[100, 10, 1, 0.1, 0.001, 0.0005], cv=cv)

    # fit model
    model.fit(X_train, y_train)
    
    # summarize chosen configuration
    print('alpha: %f' % model.alpha_)

    # predict model
    ridge_y_pred = model.predict(X_test)

    # get R^2 from true and predicted values
    #print('r2: %f' % r2_score(y_test,ridge_y_pred))
    #print('mse: %f' % mean_squared_error(y_test, ridge_y_pred))
    
    # store the test set predictions and results in a dictionary
    result = {'y_var': y_var, 'R2': r2_score(y_test,ridge_y_pred)}
    
    # append the result to the results list
    results.append(result)
    
# print the results
for result in results:
    print(result)

alpha: 0.001000
alpha: 0.001000
{'y_var': 'weighted_deprivation_score', 'R2': 0.47384611072986627}
{'y_var': 'loginc', 'R2': 0.5548209425226911}

## mosaiks + NL

In [44]:
#assign variables
data = demeaned_df.values

#select X features
X = data[:, 0:4019]

#create empty cell for resutls
results = []


# loop through each Y variable
for y_var in ['weighted_deprivation_score', 'loginc']:
    
    # select the current Y variable
    y = demeaned_df[y_var]
    
    # divide data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
    
    # define model evaluation method (k-fold crosss validation model)
    cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=111)

    # define model
    model = RidgeCV(alphas=[100, 10, 1, 0.1, 0.001, 0.0005], cv=cv)

    # fit model
    model.fit(X_train, y_train)
    
    # summarize chosen configuration
    print('alpha: %f' % model.alpha_)

    # predict model
    ridge_y_pred = model.predict(X_test)

    # get R^2 from true and predicted values
    #print('r2: %f' % r2_score(y_test,ridge_y_pred))
    #print('mse: %f' % mean_squared_error(y_test, ridge_y_pred))
    
    # store the test set predictions and results in a dictionary
    result = {'y_var': y_var, 'R2': r2_score(y_test,ridge_y_pred)}
    
    # append the result to the results list
    results.append(result)
    
# print the results
for result in results:
    print(result)

alpha: 0.001000
alpha: 0.001000
{'y_var': 'weighted_deprivation_score', 'R2': 0.5233437083893948}
{'y_var': 'loginc', 'R2': 0.6097099301503482}

## NL model

In [38]:
#assign variables
data = demeaned_df.values

#select X features
X = data[:, 4000:4019]

#create empty cell for resutls
results = []


# loop through each Y variable
for y_var in ['weighted_deprivation_score', 'loginc']:
    
    # select the current Y variable
    y = demeaned_df[y_var]
    
    # divide data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
    
    # define model evaluation method (k-fold crosss validation model)
    cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=111)

    # define model
    model = RidgeCV(alphas=[100, 10, 1, 0.1, 0.001, 0.0005], cv=cv)

    # fit model
    model.fit(X_train, y_train)
    
    # summarize chosen configuration
    print('alpha: %f' % model.alpha_)

    # predict model
    ridge_y_pred = model.predict(X_test)

    # get R^2 from true and predicted values
    #print('r2: %f' % r2_score(y_test,ridge_y_pred))
    #print('mse: %f' % mean_squared_error(y_test, ridge_y_pred))
    
    # store the test set predictions and results in a dictionary
    result = {'y_var': y_var, 'R2': r2_score(y_test,ridge_y_pred)}
    
    # append the result to the results list
    results.append(result)
    
# print the results
for result in results:
    print(result)

alpha: 10.000000
alpha: 10.000000
{'y_var': 'weighted_deprivation_score', 'R2': 0.38868929212976566}
{'y_var': 'loginc', 'R2': 0.5023855051211494}

In [ ]:
# alpha: 0.100000
# r2: 0.516376
# mse: 0.007486
# alpha: 0.100000
# r2: 0.577908
# mse: 97.711466
# alpha: 0.100000
# r2: 0.575334
# mse: 0.196135
# {'y_var': 'weighted_deprivation_score', 'R2': 0.5163755146443219}
# {'y_var': 'IWI', 'R2': 0.5779082013006809}
# {'y_var': 'loginc', 'R2': 0.5753339703939799}

## by country

## MOSAIKS model

In [43]:

#create empty cell for resutls
results = []

# loop through each Y variable
for y_var in ['weighted_deprivation_score', 'loginc']:
    
    # loop through each country
    for c in merge4['country'].unique():
        # select rows corresponding to the current country
        df_country = merge4[merge4['country'] == c]
        
        # separate X and y variables
        X = df_country.iloc[:, 1:4000]
        y = df_country[y_var]
        
        # divide data into training and test sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

        # define model evaluation method (k-fold crosss validation model)
        cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=111)

        model = RidgeCV(alphas=[100, 10, 1, 0.1, 0.001, 0.0005], cv=cv)

        # fit model
        model.fit(X_train, y_train)

        # predict model
        ridge_y_pred = model.predict(X_test)

        # get R^2 from true and predicted values
        #print('r2: %f' % r2_score(y_test,ridge_y_pred))
        #print('mse: %f' % mean_squared_error(y_test, ridge_y_pred))

        # store the test set predictions and results in a dictionary
        result = {'country': c, 'y_var': y_var, 'R2': r2_score(y_test,ridge_y_pred)}

        # append the result to the results list
        results.append(result)

    # print the results
    for result in results:
        print(result)

{'country': 'AL', 'y_var': 'weighted_deprivation_score', 'R2': 0.3761935169968358}
{'country': 'AM', 'y_var': 'weighted_deprivation_score', 'R2': 0.29659801080400305}
{'country': 'AO', 'y_var': 'weighted_deprivation_score', 'R2': 0.4479657201089411}
{'country': 'BJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.6456174529757193}
{'country': 'BU', 'y_var': 'weighted_deprivation_score', 'R2': 0.6065143696814597}
{'country': 'CM', 'y_var': 'weighted_deprivation_score', 'R2': 0.6201495817870215}
{'country': 'EG', 'y_var': 'weighted_deprivation_score', 'R2': 0.19889245326243632}
{'country': 'ET', 'y_var': 'weighted_deprivation_score', 'R2': 0.489059080619361}
{'country': 'GA', 'y_var': 'weighted_deprivation_score', 'R2': 0.5816506161704924}
{'country': 'GN', 'y_var': 'weighted_deprivation_score', 'R2': 0.6319692224100022}
{'country': 'GU', 'y_var': 'weighted_deprivation_score', 'R2': 0.4856203101941756}
{'country': 'HT', 'y_var': 'weighted_deprivation_score', 'R2': 0.5737853249519042}
{'country': 'JO', 'y_var': 'weighted_deprivation_score', 'R2': 0.1948929445491937}
{'country': 'KE', 'y_var': 'weighted_deprivation_score', 'R2': 0.5987235634746411}
{'country': 'KM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5423155134735649}
{'country': 'LB', 'y_var': 'weighted_deprivation_score', 'R2': 0.3677051644922672}
{'country': 'ML', 'y_var': 'weighted_deprivation_score', 'R2': 0.49467821508269827}
{'country': 'MM', 'y_var': 'weighted_deprivation_score', 'R2': 0.30219652029450605}
{'country': 'NG', 'y_var': 'weighted_deprivation_score', 'R2': 0.5828428925190681}
{'country': 'PH', 'y_var': 'weighted_deprivation_score', 'R2': 0.40096240081775814}
{'country': 'PK', 'y_var': 'weighted_deprivation_score', 'R2': 0.2877393079632382}
{'country': 'SL', 'y_var': 'weighted_deprivation_score', 'R2': 0.48954906298792566}
{'country': 'SN', 'y_var': 'weighted_deprivation_score', 'R2': 0.5673660673024806}
{'country': 'TJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.4276024888552}
{'country': 'TL', 'y_var': 'weighted_deprivation_score', 'R2': 0.38455027445904233}
{'country': 'TZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.4742976857057678}
{'country': 'UG', 'y_var': 'weighted_deprivation_score', 'R2': 0.5013572280469394}
{'country': 'ZA', 'y_var': 'weighted_deprivation_score', 'R2': 0.22538744233270136}
{'country': 'ZM', 'y_var': 'weighted_deprivation_score', 'R2': 0.42566115918863767}
{'country': 'BF', 'y_var': 'weighted_deprivation_score', 'R2': 0.5316676846157848}
{'country': 'GM', 'y_var': 'weighted_deprivation_score', 'R2': 0.3543584370144942}
{'country': 'IA', 'y_var': 'weighted_deprivation_score', 'R2': 0.39174315855476727}
{'country': 'KH', 'y_var': 'weighted_deprivation_score', 'R2': 0.4050524729651349}
{'country': 'MR', 'y_var': 'weighted_deprivation_score', 'R2': 0.6562198755844066}
{'country': 'MZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.7229160520009863}
{'country': 'NI', 'y_var': 'weighted_deprivation_score', 'R2': 0.40709646905987007}
{'country': 'RW', 'y_var': 'weighted_deprivation_score', 'R2': 0.4752941764018559}
{'country': 'AL', 'y_var': 'weighted_deprivation_score', 'R2': 0.3761935169968358}
{'country': 'AM', 'y_var': 'weighted_deprivation_score', 'R2': 0.29659801080400305}
{'country': 'AO', 'y_var': 'weighted_deprivation_score', 'R2': 0.4479657201089411}
{'country': 'BJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.6456174529757193}
{'country': 'BU', 'y_var': 'weighted_deprivation_score', 'R2': 0.6065143696814597}
{'country': 'CM', 'y_var': 'weighted_deprivation_score', 'R2': 0.6201495817870215}
{'country': 'EG', 'y_var': 'weighted_deprivation_score', 'R2': 0.19889245326243632}
{'country': 'ET', 'y_var': 'weighted_deprivation_score', 'R2': 0.489059080619361}
{'country': 'GA', 'y_var': 'weighted_deprivation_score', 'R2': 0.5816506161704924}
{'country': 'GN', 'y_var': 'weighted_deprivation_score', 'R2': 0.6319692224100022}
{'country': 'GU', 'y_var': 'weighted_deprivation_score', 'R2': 0.4856203101941756}
{'country': 'HT', 'y_var': 'weighted_deprivation_score', 'R2': 0.5737853249519042}
{'country': 'JO', 'y_var': 'weighted_deprivation_score', 'R2': 0.1948929445491937}
{'country': 'KE', 'y_var': 'weighted_deprivation_score', 'R2': 0.5987235634746411}
{'country': 'KM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5423155134735649}
{'country': 'LB', 'y_var': 'weighted_deprivation_score', 'R2': 0.3677051644922672}
{'country': 'ML', 'y_var': 'weighted_deprivation_score', 'R2': 0.49467821508269827}
{'country': 'MM', 'y_var': 'weighted_deprivation_score', 'R2': 0.30219652029450605}
{'country': 'NG', 'y_var': 'weighted_deprivation_score', 'R2': 0.5828428925190681}
{'country': 'PH', 'y_var': 'weighted_deprivation_score', 'R2': 0.40096240081775814}
{'country': 'PK', 'y_var': 'weighted_deprivation_score', 'R2': 0.2877393079632382}
{'country': 'SL', 'y_var': 'weighted_deprivation_score', 'R2': 0.48954906298792566}
{'country': 'SN', 'y_var': 'weighted_deprivation_score', 'R2': 0.5673660673024806}
{'country': 'TJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.4276024888552}
{'country': 'TL', 'y_var': 'weighted_deprivation_score', 'R2': 0.38455027445904233}
{'country': 'TZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.4742976857057678}
{'country': 'UG', 'y_var': 'weighted_deprivation_score', 'R2': 0.5013572280469394}
{'country': 'ZA', 'y_var': 'weighted_deprivation_score', 'R2': 0.22538744233270136}
{'country': 'ZM', 'y_var': 'weighted_deprivation_score', 'R2': 0.42566115918863767}
{'country': 'BF', 'y_var': 'weighted_deprivation_score', 'R2': 0.5316676846157848}
{'country': 'GM', 'y_var': 'weighted_deprivation_score', 'R2': 0.3543584370144942}
{'country': 'IA', 'y_var': 'weighted_deprivation_score', 'R2': 0.39174315855476727}
{'country': 'KH', 'y_var': 'weighted_deprivation_score', 'R2': 0.4050524729651349}
{'country': 'MR', 'y_var': 'weighted_deprivation_score', 'R2': 0.6562198755844066}
{'country': 'MZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.7229160520009863}
{'country': 'NI', 'y_var': 'weighted_deprivation_score', 'R2': 0.40709646905987007}
{'country': 'RW', 'y_var': 'weighted_deprivation_score', 'R2': 0.4752941764018559}
{'country': 'AL', 'y_var': 'loginc', 'R2': 0.5844694745611814}
{'country': 'AM', 'y_var': 'loginc', 'R2': 0.3002902338959058}
{'country': 'AO', 'y_var': 'loginc', 'R2': 0.5329084101127257}
{'country': 'BJ', 'y_var': 'loginc', 'R2': 0.6524695047144219}
{'country': 'BU', 'y_var': 'loginc', 'R2': 0.6652399467747845}
{'country': 'CM', 'y_var': 'loginc', 'R2': 0.717204897697235}
{'country': 'EG', 'y_var': 'loginc', 'R2': 0.6651672170741514}
{'country': 'ET', 'y_var': 'loginc', 'R2': 0.5300486922188492}
{'country': 'GA', 'y_var': 'loginc', 'R2': 0.5827187845179336}
{'country': 'GN', 'y_var': 'loginc', 'R2': 0.7441171782635723}
{'country': 'GU', 'y_var': 'loginc', 'R2': 0.6288459652353622}
{'country': 'HT', 'y_var': 'loginc', 'R2': 0.6344225316500434}
{'country': 'JO', 'y_var': 'loginc', 'R2': 0.6282460367828051}
{'country': 'KE', 'y_var': 'loginc', 'R2': 0.6515130368854849}
{'country': 'KM', 'y_var': 'loginc', 'R2': 0.6103324101810698}
{'country': 'LB', 'y_var': 'loginc', 'R2': 0.5001891654035022}
{'country': 'ML', 'y_var': 'loginc', 'R2': 0.7143487572683616}
{'country': 'MM', 'y_var': 'loginc', 'R2': 0.43849982526221176}
{'country': 'NG', 'y_var': 'loginc', 'R2': 0.5825095347595293}
{'country': 'PH', 'y_var': 'loginc', 'R2': 0.4474542350754981}
{'country': 'PK', 'y_var': 'loginc', 'R2': 0.35762660311712147}
{'country': 'SL', 'y_var': 'loginc', 'R2': 0.6683067913266517}
{'country': 'SN', 'y_var': 'loginc', 'R2': 0.6511014188467085}
{'country': 'TJ', 'y_var': 'loginc', 'R2': 0.7207352295052937}
{'country': 'TL', 'y_var': 'loginc', 'R2': 0.5547725599084601}
{'country': 'TZ', 'y_var': 'loginc', 'R2': 0.5672436978425053}
{'country': 'UG', 'y_var': 'loginc', 'R2': 0.7499164899391271}
{'country': 'ZA', 'y_var': 'loginc', 'R2': 0.3673494430928165}
{'country': 'ZM', 'y_var': 'loginc', 'R2': 0.49566884002922496}
{'country': 'BF', 'y_var': 'loginc', 'R2': 0.6846840219922011}
{'country': 'GM', 'y_var': 'loginc', 'R2': 0.8086877080991284}
{'country': 'IA', 'y_var': 'loginc', 'R2': 0.590989120655552}
{'country': 'KH', 'y_var': 'loginc', 'R2': 0.621039719795649}
{'country': 'MR', 'y_var': 'loginc', 'R2': 0.6685612149223674}
{'country': 'MZ', 'y_var': 'loginc', 'R2': 0.7221940027618887}
{'country': 'NI', 'y_var': 'loginc', 'R2': 0.41151112358705544}
{'country': 'RW', 'y_var': 'loginc', 'R2': 0.7207538770952062}

## MOSAIKS + NL

In [46]:

#create empty cell for resutls
results = []

# loop through each Y variable
for y_var in ['weighted_deprivation_score', 'loginc']:
    
    # loop through each country
    for c in merge4['country'].unique():
        # select rows corresponding to the current country
        df_country = merge4[merge4['country'] == c]
        
        # separate X and y variables
        X = df_country.iloc[:, 1:4020]
        y = df_country[y_var]
        
        # divide data into training and test sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

        # define model evaluation method (k-fold crosss validation model)
        cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=111)

        model = RidgeCV(alphas=[100, 10, 1, 0.1, 0.001, 0.0005], cv=cv)

        # fit model
        model.fit(X_train, y_train)

        # predict model
        ridge_y_pred = model.predict(X_test)

        # get R^2 from true and predicted values
        #print('r2: %f' % r2_score(y_test,ridge_y_pred))
        #print('mse: %f' % mean_squared_error(y_test, ridge_y_pred))

        # store the test set predictions and results in a dictionary
        result = {'country': c, 'y_var': y_var, 'R2': r2_score(y_test,ridge_y_pred)}

        # append the result to the results list
        results.append(result)

    # print the results
    for result in results:
        print(result)

{'country': 'AL', 'y_var': 'weighted_deprivation_score', 'R2': 0.3912322450082001}
{'country': 'AM', 'y_var': 'weighted_deprivation_score', 'R2': 0.4720990202529165}
{'country': 'AO', 'y_var': 'weighted_deprivation_score', 'R2': 0.6841850053645314}
{'country': 'BJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.659907353983797}
{'country': 'BU', 'y_var': 'weighted_deprivation_score', 'R2': 0.626210018640276}
{'country': 'CM', 'y_var': 'weighted_deprivation_score', 'R2': 0.6682612463216023}
{'country': 'EG', 'y_var': 'weighted_deprivation_score', 'R2': 0.19931408078396717}
{'country': 'ET', 'y_var': 'weighted_deprivation_score', 'R2': 0.5375548391188669}
{'country': 'GA', 'y_var': 'weighted_deprivation_score', 'R2': 0.5964231499700392}
{'country': 'GN', 'y_var': 'weighted_deprivation_score', 'R2': 0.6329666374056432}
{'country': 'GU', 'y_var': 'weighted_deprivation_score', 'R2': 0.5518084661396419}
{'country': 'HT', 'y_var': 'weighted_deprivation_score', 'R2': 0.560900563018742}
{'country': 'JO', 'y_var': 'weighted_deprivation_score', 'R2': 0.24083440841971548}
{'country': 'KE', 'y_var': 'weighted_deprivation_score', 'R2': 0.6277585853369578}
{'country': 'KM', 'y_var': 'weighted_deprivation_score', 'R2': 0.571394022816091}
{'country': 'LB', 'y_var': 'weighted_deprivation_score', 'R2': 0.41046623860649645}
{'country': 'ML', 'y_var': 'weighted_deprivation_score', 'R2': 0.6432871203828232}
{'country': 'MM', 'y_var': 'weighted_deprivation_score', 'R2': 0.34793862507686635}
{'country': 'NG', 'y_var': 'weighted_deprivation_score', 'R2': 0.626888428546807}
{'country': 'PH', 'y_var': 'weighted_deprivation_score', 'R2': 0.37261724052895406}
{'country': 'PK', 'y_var': 'weighted_deprivation_score', 'R2': 0.36138632341231935}
{'country': 'SL', 'y_var': 'weighted_deprivation_score', 'R2': 0.4933014915641709}
{'country': 'SN', 'y_var': 'weighted_deprivation_score', 'R2': 0.7034630263051331}
{'country': 'TJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.4863641888373308}
{'country': 'TL', 'y_var': 'weighted_deprivation_score', 'R2': 0.4568249327339464}
{'country': 'TZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.48570451632637945}
{'country': 'UG', 'y_var': 'weighted_deprivation_score', 'R2': 0.49052376856545243}
{'country': 'ZA', 'y_var': 'weighted_deprivation_score', 'R2': 0.27837972015732104}
{'country': 'ZM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5894490181042799}
{'country': 'BF', 'y_var': 'weighted_deprivation_score', 'R2': 0.5853660041951206}
{'country': 'GM', 'y_var': 'weighted_deprivation_score', 'R2': 0.3667365902577636}
{'country': 'IA', 'y_var': 'weighted_deprivation_score', 'R2': 0.472114056918441}
{'country': 'KH', 'y_var': 'weighted_deprivation_score', 'R2': 0.42063447290783196}
{'country': 'MR', 'y_var': 'weighted_deprivation_score', 'R2': 0.6141058617969022}
{'country': 'MZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.7766411941287135}
{'country': 'NI', 'y_var': 'weighted_deprivation_score', 'R2': 0.5763292392197974}
{'country': 'RW', 'y_var': 'weighted_deprivation_score', 'R2': 0.4676106007217362}
{'country': 'AL', 'y_var': 'weighted_deprivation_score', 'R2': 0.3912322450082001}
{'country': 'AM', 'y_var': 'weighted_deprivation_score', 'R2': 0.4720990202529165}
{'country': 'AO', 'y_var': 'weighted_deprivation_score', 'R2': 0.6841850053645314}
{'country': 'BJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.659907353983797}
{'country': 'BU', 'y_var': 'weighted_deprivation_score', 'R2': 0.626210018640276}
{'country': 'CM', 'y_var': 'weighted_deprivation_score', 'R2': 0.6682612463216023}
{'country': 'EG', 'y_var': 'weighted_deprivation_score', 'R2': 0.19931408078396717}
{'country': 'ET', 'y_var': 'weighted_deprivation_score', 'R2': 0.5375548391188669}
{'country': 'GA', 'y_var': 'weighted_deprivation_score', 'R2': 0.5964231499700392}
{'country': 'GN', 'y_var': 'weighted_deprivation_score', 'R2': 0.6329666374056432}
{'country': 'GU', 'y_var': 'weighted_deprivation_score', 'R2': 0.5518084661396419}
{'country': 'HT', 'y_var': 'weighted_deprivation_score', 'R2': 0.560900563018742}
{'country': 'JO', 'y_var': 'weighted_deprivation_score', 'R2': 0.24083440841971548}
{'country': 'KE', 'y_var': 'weighted_deprivation_score', 'R2': 0.6277585853369578}
{'country': 'KM', 'y_var': 'weighted_deprivation_score', 'R2': 0.571394022816091}
{'country': 'LB', 'y_var': 'weighted_deprivation_score', 'R2': 0.41046623860649645}
{'country': 'ML', 'y_var': 'weighted_deprivation_score', 'R2': 0.6432871203828232}
{'country': 'MM', 'y_var': 'weighted_deprivation_score', 'R2': 0.34793862507686635}
{'country': 'NG', 'y_var': 'weighted_deprivation_score', 'R2': 0.626888428546807}
{'country': 'PH', 'y_var': 'weighted_deprivation_score', 'R2': 0.37261724052895406}
{'country': 'PK', 'y_var': 'weighted_deprivation_score', 'R2': 0.36138632341231935}
{'country': 'SL', 'y_var': 'weighted_deprivation_score', 'R2': 0.4933014915641709}
{'country': 'SN', 'y_var': 'weighted_deprivation_score', 'R2': 0.7034630263051331}
{'country': 'TJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.4863641888373308}
{'country': 'TL', 'y_var': 'weighted_deprivation_score', 'R2': 0.4568249327339464}
{'country': 'TZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.48570451632637945}
{'country': 'UG', 'y_var': 'weighted_deprivation_score', 'R2': 0.49052376856545243}
{'country': 'ZA', 'y_var': 'weighted_deprivation_score', 'R2': 0.27837972015732104}
{'country': 'ZM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5894490181042799}
{'country': 'BF', 'y_var': 'weighted_deprivation_score', 'R2': 0.5853660041951206}
{'country': 'GM', 'y_var': 'weighted_deprivation_score', 'R2': 0.3667365902577636}
{'country': 'IA', 'y_var': 'weighted_deprivation_score', 'R2': 0.472114056918441}
{'country': 'KH', 'y_var': 'weighted_deprivation_score', 'R2': 0.42063447290783196}
{'country': 'MR', 'y_var': 'weighted_deprivation_score', 'R2': 0.6141058617969022}
{'country': 'MZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.7766411941287135}
{'country': 'NI', 'y_var': 'weighted_deprivation_score', 'R2': 0.5763292392197974}
{'country': 'RW', 'y_var': 'weighted_deprivation_score', 'R2': 0.4676106007217362}
{'country': 'AL', 'y_var': 'loginc', 'R2': 0.6108170491038352}
{'country': 'AM', 'y_var': 'loginc', 'R2': 0.29714253780582134}
{'country': 'AO', 'y_var': 'loginc', 'R2': 0.7930721780249033}
{'country': 'BJ', 'y_var': 'loginc', 'R2': 0.6724731609456006}
{'country': 'BU', 'y_var': 'loginc', 'R2': 0.6902843134176284}
{'country': 'CM', 'y_var': 'loginc', 'R2': 0.7778298714196502}
{'country': 'EG', 'y_var': 'loginc', 'R2': 0.6717366622828889}
{'country': 'ET', 'y_var': 'loginc', 'R2': 0.6330990186111156}
{'country': 'GA', 'y_var': 'loginc', 'R2': 0.6723669647874628}
{'country': 'GN', 'y_var': 'loginc', 'R2': 0.7525484101601326}
{'country': 'GU', 'y_var': 'loginc', 'R2': 0.6886896845638224}
{'country': 'HT', 'y_var': 'loginc', 'R2': 0.6707331331878071}
{'country': 'JO', 'y_var': 'loginc', 'R2': 0.6469159250536706}
{'country': 'KE', 'y_var': 'loginc', 'R2': 0.6758417846053177}
{'country': 'KM', 'y_var': 'loginc', 'R2': 0.6553988980592484}
{'country': 'LB', 'y_var': 'loginc', 'R2': 0.5634609124280674}
{'country': 'ML', 'y_var': 'loginc', 'R2': 0.7638987325432411}
{'country': 'MM', 'y_var': 'loginc', 'R2': 0.5130714930878445}
{'country': 'NG', 'y_var': 'loginc', 'R2': 0.6875124390282383}
{'country': 'PH', 'y_var': 'loginc', 'R2': 0.44456040660810947}
{'country': 'PK', 'y_var': 'loginc', 'R2': 0.4621904882935923}
{'country': 'SL', 'y_var': 'loginc', 'R2': 0.6613165075901988}
{'country': 'SN', 'y_var': 'loginc', 'R2': 0.7713234253367659}
{'country': 'TJ', 'y_var': 'loginc', 'R2': 0.784803608678905}
{'country': 'TL', 'y_var': 'loginc', 'R2': 0.6044657980619219}
{'country': 'TZ', 'y_var': 'loginc', 'R2': 0.6006363161598374}
{'country': 'UG', 'y_var': 'loginc', 'R2': 0.7366671090846854}
{'country': 'ZA', 'y_var': 'loginc', 'R2': 0.3995805874140883}
{'country': 'ZM', 'y_var': 'loginc', 'R2': 0.6695963393030101}
{'country': 'BF', 'y_var': 'loginc', 'R2': 0.696939768248048}
{'country': 'GM', 'y_var': 'loginc', 'R2': 0.8323173151644614}
{'country': 'IA', 'y_var': 'loginc', 'R2': 0.6321213031805513}
{'country': 'KH', 'y_var': 'loginc', 'R2': 0.6435061655164929}
{'country': 'MR', 'y_var': 'loginc', 'R2': 0.6377133521291404}
{'country': 'MZ', 'y_var': 'loginc', 'R2': 0.760147762615466}
{'country': 'NI', 'y_var': 'loginc', 'R2': 0.5690394281981848}
{'country': 'RW', 'y_var': 'loginc', 'R2': 0.7101121552643705}

## NL

In [39]:

#create empty cell for resutls
results = []

# loop through each Y variable
for y_var in ['weighted_deprivation_score', 'loginc']:
    
    # loop through each country
    for c in merge4['country'].unique():
        # select rows corresponding to the current country
        df_country = merge4[merge4['country'] == c]
        
        # separate X and y variables
        X = df_country.iloc[:, 4000:4019]
        y = df_country[y_var]
        
        # divide data into training and test sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

        # define model evaluation method (k-fold crosss validation model)
        cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=111)

        model = RidgeCV(alphas=[100, 10, 1, 0.1, 0.001, 0.0005], cv=cv)

        # fit model
        model.fit(X_train, y_train)

        # predict model
        ridge_y_pred = model.predict(X_test)

        # get R^2 from true and predicted values
        #print('r2: %f' % r2_score(y_test,ridge_y_pred))
        #print('mse: %f' % mean_squared_error(y_test, ridge_y_pred))

        # store the test set predictions and results in a dictionary
        result = {'country': c, 'y_var': y_var, 'R2': r2_score(y_test,ridge_y_pred)}

        # append the result to the results list
        results.append(result)

    # print the results
    for result in results:
        print(result)

{'country': 'AL', 'y_var': 'weighted_deprivation_score', 'R2': 0.2816601834584799}
{'country': 'AM', 'y_var': 'weighted_deprivation_score', 'R2': 0.22194196613288486}
{'country': 'AO', 'y_var': 'weighted_deprivation_score', 'R2': 0.6532720424514662}
{'country': 'BJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.5666730361449055}
{'country': 'BU', 'y_var': 'weighted_deprivation_score', 'R2': 0.570228753696996}
{'country': 'CM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5485170850146001}
{'country': 'EG', 'y_var': 'weighted_deprivation_score', 'R2': 0.13241462095408407}
{'country': 'ET', 'y_var': 'weighted_deprivation_score', 'R2': 0.5880991734795912}
{'country': 'GA', 'y_var': 'weighted_deprivation_score', 'R2': 0.5828563361411809}
{'country': 'GN', 'y_var': 'weighted_deprivation_score', 'R2': 0.5794455970036991}
{'country': 'GU', 'y_var': 'weighted_deprivation_score', 'R2': 0.4675216799359744}
{'country': 'HT', 'y_var': 'weighted_deprivation_score', 'R2': 0.3868435423348856}
{'country': 'JO', 'y_var': 'weighted_deprivation_score', 'R2': 0.15331566031072796}
{'country': 'KE', 'y_var': 'weighted_deprivation_score', 'R2': 0.4234786403992876}
{'country': 'KM', 'y_var': 'weighted_deprivation_score', 'R2': 0.3591902048564768}
{'country': 'LB', 'y_var': 'weighted_deprivation_score', 'R2': 0.4040615393072281}
{'country': 'ML', 'y_var': 'weighted_deprivation_score', 'R2': 0.6546664074188119}
{'country': 'MM', 'y_var': 'weighted_deprivation_score', 'R2': 0.39671489598941323}
{'country': 'NG', 'y_var': 'weighted_deprivation_score', 'R2': 0.43309701845257365}
{'country': 'PH', 'y_var': 'weighted_deprivation_score', 'R2': 0.2974092425184638}
{'country': 'PK', 'y_var': 'weighted_deprivation_score', 'R2': 0.34827031511152107}
{'country': 'SL', 'y_var': 'weighted_deprivation_score', 'R2': 0.46796543494138276}
{'country': 'SN', 'y_var': 'weighted_deprivation_score', 'R2': 0.648842194189095}
{'country': 'TJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.38055775424925553}
{'country': 'TL', 'y_var': 'weighted_deprivation_score', 'R2': 0.3907391110814227}
{'country': 'TZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.46386336099490066}
{'country': 'UG', 'y_var': 'weighted_deprivation_score', 'R2': 0.32008665213551823}
{'country': 'ZA', 'y_var': 'weighted_deprivation_score', 'R2': 0.23671401296555739}
{'country': 'ZM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5745283433811094}
{'country': 'BF', 'y_var': 'weighted_deprivation_score', 'R2': 0.5700328643111637}
{'country': 'GM', 'y_var': 'weighted_deprivation_score', 'R2': 0.43105921539764525}
{'country': 'IA', 'y_var': 'weighted_deprivation_score', 'R2': 0.33532562637985563}
{'country': 'KH', 'y_var': 'weighted_deprivation_score', 'R2': 0.3875790887376007}
{'country': 'MR', 'y_var': 'weighted_deprivation_score', 'R2': 0.46903063282840374}
{'country': 'MZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.7469535417673092}
{'country': 'NI', 'y_var': 'weighted_deprivation_score', 'R2': 0.6040813581276734}
{'country': 'RW', 'y_var': 'weighted_deprivation_score', 'R2': 0.4304082802636807}
{'country': 'AL', 'y_var': 'weighted_deprivation_score', 'R2': 0.2816601834584799}
{'country': 'AM', 'y_var': 'weighted_deprivation_score', 'R2': 0.22194196613288486}
{'country': 'AO', 'y_var': 'weighted_deprivation_score', 'R2': 0.6532720424514662}
{'country': 'BJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.5666730361449055}
{'country': 'BU', 'y_var': 'weighted_deprivation_score', 'R2': 0.570228753696996}
{'country': 'CM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5485170850146001}
{'country': 'EG', 'y_var': 'weighted_deprivation_score', 'R2': 0.13241462095408407}
{'country': 'ET', 'y_var': 'weighted_deprivation_score', 'R2': 0.5880991734795912}
{'country': 'GA', 'y_var': 'weighted_deprivation_score', 'R2': 0.5828563361411809}
{'country': 'GN', 'y_var': 'weighted_deprivation_score', 'R2': 0.5794455970036991}
{'country': 'GU', 'y_var': 'weighted_deprivation_score', 'R2': 0.4675216799359744}
{'country': 'HT', 'y_var': 'weighted_deprivation_score', 'R2': 0.3868435423348856}
{'country': 'JO', 'y_var': 'weighted_deprivation_score', 'R2': 0.15331566031072796}
{'country': 'KE', 'y_var': 'weighted_deprivation_score', 'R2': 0.4234786403992876}
{'country': 'KM', 'y_var': 'weighted_deprivation_score', 'R2': 0.3591902048564768}
{'country': 'LB', 'y_var': 'weighted_deprivation_score', 'R2': 0.4040615393072281}
{'country': 'ML', 'y_var': 'weighted_deprivation_score', 'R2': 0.6546664074188119}
{'country': 'MM', 'y_var': 'weighted_deprivation_score', 'R2': 0.39671489598941323}
{'country': 'NG', 'y_var': 'weighted_deprivation_score', 'R2': 0.43309701845257365}
{'country': 'PH', 'y_var': 'weighted_deprivation_score', 'R2': 0.2974092425184638}
{'country': 'PK', 'y_var': 'weighted_deprivation_score', 'R2': 0.34827031511152107}
{'country': 'SL', 'y_var': 'weighted_deprivation_score', 'R2': 0.46796543494138276}
{'country': 'SN', 'y_var': 'weighted_deprivation_score', 'R2': 0.648842194189095}
{'country': 'TJ', 'y_var': 'weighted_deprivation_score', 'R2': 0.38055775424925553}
{'country': 'TL', 'y_var': 'weighted_deprivation_score', 'R2': 0.3907391110814227}
{'country': 'TZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.46386336099490066}
{'country': 'UG', 'y_var': 'weighted_deprivation_score', 'R2': 0.32008665213551823}
{'country': 'ZA', 'y_var': 'weighted_deprivation_score', 'R2': 0.23671401296555739}
{'country': 'ZM', 'y_var': 'weighted_deprivation_score', 'R2': 0.5745283433811094}
{'country': 'BF', 'y_var': 'weighted_deprivation_score', 'R2': 0.5700328643111637}
{'country': 'GM', 'y_var': 'weighted_deprivation_score', 'R2': 0.43105921539764525}
{'country': 'IA', 'y_var': 'weighted_deprivation_score', 'R2': 0.33532562637985563}
{'country': 'KH', 'y_var': 'weighted_deprivation_score', 'R2': 0.3875790887376007}
{'country': 'MR', 'y_var': 'weighted_deprivation_score', 'R2': 0.46903063282840374}
{'country': 'MZ', 'y_var': 'weighted_deprivation_score', 'R2': 0.7469535417673092}
{'country': 'NI', 'y_var': 'weighted_deprivation_score', 'R2': 0.6040813581276734}
{'country': 'RW', 'y_var': 'weighted_deprivation_score', 'R2': 0.4304082802636807}
{'country': 'AL', 'y_var': 'loginc', 'R2': 0.593696780394753}
{'country': 'AM', 'y_var': 'loginc', 'R2': 0.2172696237732148}
{'country': 'AO', 'y_var': 'loginc', 'R2': 0.6979833027329856}
{'country': 'BJ', 'y_var': 'loginc', 'R2': 0.6590215315123351}
{'country': 'BU', 'y_var': 'loginc', 'R2': 0.6711243733937999}
{'country': 'CM', 'y_var': 'loginc', 'R2': 0.6499762528162227}
{'country': 'EG', 'y_var': 'loginc', 'R2': 0.44110099125328395}
{'country': 'ET', 'y_var': 'loginc', 'R2': 0.7007750878861041}
{'country': 'GA', 'y_var': 'loginc', 'R2': 0.6757977889136595}
{'country': 'GN', 'y_var': 'loginc', 'R2': 0.7060306365448055}
{'country': 'GU', 'y_var': 'loginc', 'R2': 0.5958926076921863}
{'country': 'HT', 'y_var': 'loginc', 'R2': 0.5733203817996717}
{'country': 'JO', 'y_var': 'loginc', 'R2': 0.4185160996733067}
{'country': 'KE', 'y_var': 'loginc', 'R2': 0.5381025948979712}
{'country': 'KM', 'y_var': 'loginc', 'R2': 0.37259748431706374}
{'country': 'LB', 'y_var': 'loginc', 'R2': 0.5827024116733687}
{'country': 'ML', 'y_var': 'loginc', 'R2': 0.764746879494038}
{'country': 'MM', 'y_var': 'loginc', 'R2': 0.5581814383189438}
{'country': 'NG', 'y_var': 'loginc', 'R2': 0.6220967505415429}
{'country': 'PH', 'y_var': 'loginc', 'R2': 0.3942656930841014}
{'country': 'PK', 'y_var': 'loginc', 'R2': 0.4061826353539889}
{'country': 'SL', 'y_var': 'loginc', 'R2': 0.6123729900802339}
{'country': 'SN', 'y_var': 'loginc', 'R2': 0.7217937181526873}
{'country': 'TJ', 'y_var': 'loginc', 'R2': 0.6691134596074368}
{'country': 'TL', 'y_var': 'loginc', 'R2': 0.5495808413282701}
{'country': 'TZ', 'y_var': 'loginc', 'R2': 0.5870089226031012}
{'country': 'UG', 'y_var': 'loginc', 'R2': 0.4801612652938999}
{'country': 'ZA', 'y_var': 'loginc', 'R2': 0.2942179204779749}
{'country': 'ZM', 'y_var': 'loginc', 'R2': 0.6387726192901866}
{'country': 'BF', 'y_var': 'loginc', 'R2': 0.6173560278462609}
{'country': 'GM', 'y_var': 'loginc', 'R2': 0.7896291410039072}
{'country': 'IA', 'y_var': 'loginc', 'R2': 0.51642520529296}
{'country': 'KH', 'y_var': 'loginc', 'R2': 0.594826757309437}
{'country': 'MR', 'y_var': 'loginc', 'R2': 0.5333116189045088}
{'country': 'MZ', 'y_var': 'loginc', 'R2': 0.6859474971938573}
{'country': 'NI', 'y_var': 'loginc', 'R2': 0.608057551749984}
{'country': 'RW', 'y_var': 'loginc', 'R2': 0.5999197458489768}